all:
#	g++ -O3 -std=c++11 -Wno-write-strings gen_db.cpp -o bin/gen_db
	g++ -O3 -std=c++11 -Wno-write-strings new_db.cpp -o bin/new_db
	g++ -O3 -Wno-write-strings -std=c++11 run.cpp -o bin/15_puzzle

clean:
	rm bin/*
	rm db/*
	